### PR TITLE
Add MATE Panel (Gtk3) support

### PR DESCRIPTION
**Pull request by XRevan86**
This also makes build of GNOME Flashback Panel applet disabled by default as I didn't find a way to make it conditional otherwise using autovala (not all distributions provide GNOME Flashback in their official repositories).

### CODE REVIEW

**Comment by rastersoft** [comment]
I was to add this, but the patches lack the MATE code itself (mate-applet.txt and the source files themselves).

**Comment by XRevan86** [comment]
Fixed.

**Comment by rastersoft** [comment]
I created a branch and added your code, but with some modifications. Unfortunately I'm unable to make it work, not sure if it is because Debian has Mate 1.14 and maybe it is too old... don't know. Could you check it, please? The branch is called "mate"

**Comment by XRevan86** [comment]
If MATE is built with Gtk3, then it should work. Otherwise, it won't. 
I rebased stuff from the branch back into this merge request :-).

**Pull request merged**
